[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.8.0"
hdk = "=0.7.0"
serde = "1.0"
holochain_serialized_bytes = "=0.0.57"
getrandom = { version = "0.2", features = ["custom"] }


[workspace.dependencies.ping_2_pong]
path = "dnas/ping_2_pong/zomes/coordinator/ping_2_pong"

[workspace.dependencies.ping_2_pong_integrity]
path = "dnas/ping_2_pong/zomes/integrity/ping_2_pong"
